// Code generated by scorix. DO NOT EDIT.

// Package events is the typed event layer generated from @event annotations in
// the proto: topic constants, Go->JS emit helpers and JS->Go subscribers.
// Topics are part of the IPC contract — never emit or subscribe raw strings.
package events

import (
	"context"
	"encoding/json"

	"github.com/tradalab/scorix/app"

	"{{ .Module }}/internal/types"
)

// Emitter is the Go->JS event sink. *app.App satisfies it directly; service
// contexts satisfy it by delegating to app.Emit / app.EmitTo.
type Emitter interface {
	Emit(name string, data any)
	EmitTo(client app.ClientID, name string, data any) bool
}

// Registrar registers a JS->Go event handler — pass app.Event or svcCtx.On.
type Registrar func(name string, fn func(context.Context, json.RawMessage))

const (
{{- range .OutEvents }}
	// Event{{ .EventGoName }} — server push (Go -> JS).
	Event{{ .EventGoName }} = "{{ .EventName }}"
{{- end }}
{{- range .InEvents }}
	// Event{{ .EventGoName }} — frontend event (JS -> Go).
	Event{{ .EventGoName }} = "{{ .EventName }}"
{{- end }}
)
{{ range .OutEvents }}
// Emit{{ .EventGoName }} broadcasts to every connected frontend.
func Emit{{ .EventGoName }}(e Emitter, p *{{ .RequestGoType }}) {
	e.Emit(Event{{ .EventGoName }}, p)
}

// Emit{{ .EventGoName }}To targets one frontend; reports whether it is still connected.
func Emit{{ .EventGoName }}To(e Emitter, client app.ClientID, p *{{ .RequestGoType }}) bool {
	return e.EmitTo(client, Event{{ .EventGoName }}, p)
}

// Emit{{ .EventGoName }}Ctx targets the frontend bound to ctx — the client that
// invoked the current command/event. With no bound client (Go->Go invoke,
// tests) it broadcasts. Returns false when the bound client has disconnected,
// so long-running pumps can stop producing for a dead consumer.
func Emit{{ .EventGoName }}Ctx(ctx context.Context, e Emitter, p *{{ .RequestGoType }}) bool {
	if client, ok := app.ClientFrom(ctx); ok {
		return Emit{{ .EventGoName }}To(e, client, p)
	}
	Emit{{ .EventGoName }}(e, p)
	return true
}
{{ end }}
{{- range .InEvents }}
// On{{ .EventGoName }} registers the typed handler for "{{ .EventName }}".
// Malformed payloads are dropped. Use app.ClientFrom(ctx) inside the handler
// to reply-emit to the sending client only.
func On{{ .EventGoName }}(reg Registrar, fn func(ctx context.Context, p *{{ .RequestGoType }})) {
	reg(Event{{ .EventGoName }}, func(ctx context.Context, raw json.RawMessage) {
		var p {{ .RequestGoType }}
		if len(raw) > 0 && string(raw) != "null" {
			if err := json.Unmarshal(raw, &p); err != nil {
				return
			}
		}
		fn(ctx, &p)
	})
}
{{ end }}
