// Code generated by scorix. DO NOT EDIT.
package handler

import (
	"context"
	"encoding/json"

	"github.com/tradalab/scorix/app"
{{- range .Services }}
{{- if .RPCs }}
	"{{ $.Module }}/internal/logic/{{ .Package }}"
{{- end }}
{{- end }}
	"{{ .Module }}/internal/svc"
	"{{ .Module }}/internal/types"
)

// reg registers one command on the app: it unmarshals the JSON payload into
// *Req and dispatches to the logic.
func reg[Req any](a *app.App, name string, call func(context.Context, *Req) (any, error)) {
	a.Command(name, func(ctx context.Context, data json.RawMessage, _ app.Stream) (any, error) {
		var req Req
		if len(data) > 0 && string(data) != "null" {
			if err := json.Unmarshal(data, &req); err != nil {
				return nil, err
			}
		}
		return call(ctx, &req)
	})
}

func RegisterHandlers(a *app.App, svcCtx *svc.ServiceContext) {
{{- range .Services }}
{{- $svc := . }}
{{- range .RPCs }}
	reg(a, "{{ .CommandName }}", func(ctx context.Context, r *{{ .RequestGoType }}) (any, error) {
		h := func(ctx context.Context, a any) (any, error) {
			return {{ $svc.Package }}.New{{ .LogicName }}(ctx, svcCtx).{{ .MethodName }}(a.(*{{ .RequestGoType }}))
		}
{{- range .Middlewares }}
		h = svcCtx.{{ . }}Middleware(h)
{{- end }}
		return h(ctx, r)
	})
{{- end }}
{{- end }}
}

var _ = types.Empty{}
