// Code generated by scorix.
package main

import (
	"embed"
	"flag"
	"fmt"
	"os"
	"strings"

	scorix "github.com/tradalab/scorix/kernel"
	"{{ .Module }}/internal/handler"
	"{{ .Module }}/internal/svc"
)

//go:embed all:.scorix/dist
var embeddedPublic embed.FS

//go:embed etc/app.yaml
var configFile []byte

func main() {
	mode := flag.String("mode", envOr("SCORIX_RUN_MODE", "desktop"), "run mode: desktop, web, cli")
	config := flag.String("config", "etc/app.yaml", "config file path")
	assets := flag.String("assets", "shell/dist", "static assets directory")
	flag.Parse()

	switch strings.ToLower(*mode) {
	case "desktop", "app":
		os.Setenv("SCORIX_MODE", "app")
	case "web", "server":
		os.Setenv("SCORIX_MODE", "web")
	case "cli":
		os.Setenv("SCORIX_MODE", "web")
	default:
		panic(fmt.Errorf("unsupported mode %q", *mode))
	}

	configOption := scorix.WithConfigData(configFile)
	if _, err := os.Stat(*config); err == nil {
		configOption = scorix.WithConfigFile(*config)
	}

	app := scorix.MustNew(
		[]scorix.InitOption{
			configOption,
		},
		scorix.WithAssets(embeddedPublic, ".scorix/dist"),
	)

	// Prefer external assets if they exist (development mode)
	if _, err := os.Stat(*assets); err == nil {
		app.Cfg().AssetFs = os.DirFS(*assets)
		app.Cfg().AssetFsPath = ""
	}

	svcCtx := svc.NewServiceContext(app.Cfg(), app)
	handler.RegisterHandlers(svcCtx)

	if strings.EqualFold(*mode, "cli") {
		fmt.Println("Scorix CLI mode")
		fmt.Println("registered commands:")
		for _, name := range handler.CommandNames() {
			fmt.Println(" -", name)
		}
		return
	}

	if err := app.Run(); err != nil {
		panic(err)
	}
}

func envOr(key string, fallback string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return fallback
}
