// Code generated by scorix.
package main

import (
	"embed"
	"flag"
	"io/fs"
	"log"

	"{{ .Module }}/internal/handler"
	"{{ .Module }}/internal/svc"
	"github.com/tradalab/scorix/app"
)

//go:embed all:.scorix/dist
var embeddedPublic embed.FS

func main() {
	log.SetFlags(log.Ltime)
	mode := flag.String("mode", "app", "run mode: app | web")
	addr := flag.String("addr", ":8080", "web listen address (web mode)")
	flag.Parse()

	site, err := fs.Sub(embeddedPublic, ".scorix/dist")
	if err != nil {
		log.Fatal(err)
	}

	a, err := app.New(app.Options{
		Title: "{{ .Module }}",
		URL:   "scorix://app/index.html",
	})
	if err != nil {
		log.Fatal(err)
	}
	a.Serve("scorix", site) // in-process assets via scorix:// (no localhost)

	sc := svc.NewServiceContext(a)
	handler.RegisterHandlers(a, sc)

	if *mode == "web" {
		log.Printf("serving on http://localhost%s", *addr)
		if err := a.RunWeb(*addr); err != nil {
			log.Fatal(err)
		}
		return
	}
	if err := a.Run(); err != nil {
		log.Fatal(err)
	}
}
