// Code generated by scorix.
package main

import (
	"embed"
	"flag"
	"io/fs"
	"log"

	"{{ .Module }}/internal/handler"
	"{{ .Module }}/internal/svc"
	"github.com/tradalab/scorix/app"
)

//go:embed all:.scorix/dist
var embeddedPublic embed.FS

// scorix.yaml is the single config source: app.New reads the runtime manifest
// sections (app/window/security/modules); CLI build-recipe keys are ignored.
//
//go:embed scorix.yaml
var manifest []byte

func main() {
	log.SetFlags(log.Ltime)
	mode := flag.String("mode", "app", "run mode: app | web")
	addr := flag.String("addr", "", "web listen address override (default: manifest web.host:port / SCORIX_WEB_*)")
	flag.Parse()

	site, err := fs.Sub(embeddedPublic, ".scorix/dist")
	if err != nil {
		log.Fatal(err)
	}

	a, err := app.New(app.Options{
		URL:      "scorix://app/index.html",
		Manifest: manifest,
	})
	if err != nil {
		log.Fatal(err)
	}
	a.Serve("scorix", site) // in-process assets via scorix:// (no localhost)

	sc := svc.NewServiceContext(a)
	handler.RegisterHandlers(a, sc)

	if *mode == "web" {
		listen := *addr
		if listen == "" {
			listen = a.WebAddr()
		}
		log.Printf("serving on http://%s", listen)
		if err := a.RunWeb(listen); err != nil {
			log.Fatal(err)
		}
		return
	}
	if err := a.Run(); err != nil {
		log.Fatal(err)
	}
}
