// Code generated by scorix.
package middleware

import "context"

func {{ .ExportedName }}Middleware(next func(context.Context, any) (any, error)) func(context.Context, any) (any, error) {
	return func(ctx context.Context, args any) (any, error) {
		// TODO: add middleware logic
		return next(ctx, args)
	}
}
