app:
  name: chat
  version: 1.0.0
  identifier: com.tradalab.scorix.chat
  description: "Chat"
  authors: [ "TradaLab Team" ]
  license: "UNLICENSE"
  icon: "assets/icon.ico"

window:
  title: Chat
  width: 480
  height: 480
  debug: true

security:
  csp: none
  allow_right_click: true
  allowlist:
    fs: true
    shell: true
    http: true
    clipboard: true
    notification: true

logger:
  level: debug
  format: console        # console, json
  output: stdout      # stdout, file, both
  file: logs/app.log
  max_size: 10        # MB
  max_age: 7          # days

extensions: