/**
 * Code generated by scorix. DO NOT EDIT.
 */
import scorix from "@/lib/scorix";
import type * as T from "@/types";
{{ range .Services }}
export const {{ .Package }} = {
{{- range .RPCs }}
  {{ .MethodName | lower }}: (params: T.{{ .RequestTSType }}) => scorix.invoke<T.{{ .ResultTSType }}>("{{ .CommandName }}", params),
{{- end }}
};
{{ end }}
