"use client";
/**
 * Code generated by scorix. DO NOT EDIT.
 *
 * React hooks over the typed event subscriptions in "@/api" — subscribe on
 * mount, clean up on unmount, latest-callback semantics (no resubscribe when
 * the callback identity changes).
 */
import * as React from "react";
import { events } from "@/api";
import type * as T from "@/types";
{{ range .OutEvents }}
/** Subscribe to "{{ .EventName }}" for the lifetime of the component. */
export function use{{ .EventGoName }}Event(
  cb: (data: T.{{ .RequestTSType }}, error?: string) => void,
  enabled: boolean = true,
) {
  const ref = React.useRef(cb);
  ref.current = cb;
  React.useEffect(() => {
    if (!enabled) return;
    return events.on{{ .EventGoName }}((data, error) => ref.current(data, error));
  }, [enabled]);
}
{{ end }}
