// Code generated by scorix. DO NOT EDIT.
package handler

import (
	"context"

{{- range .Services }}
	"{{ $.Module }}/internal/logic/{{ .Package }}"
{{- end }}
	"{{ .Module }}/internal/svc"
	"{{ .Module }}/internal/types"
)

func RegisterHandlers(svcCtx *svc.ServiceContext) {
	handlers := map[string]any{
{{- range .Services }}
{{- $svc := . }}
{{- range .RPCs }}
		"{{ .CommandName }}": func(ctx context.Context, args *{{ .RequestGoType }}) (interface{}, error) {
			h := func(ctx context.Context, a any) (any, error) {
				return {{ $svc.Package }}.New{{ .LogicName }}(ctx, svcCtx).{{ .MethodName }}(a.(*{{ .RequestGoType }}))
			}
{{- range .Middlewares }}
			h = svcCtx.{{ . }}Middleware(h)
{{- end }}
			return h(ctx, args)
		},
{{- end }}
{{- end }}
	}
	for name, handler := range handlers {
		svcCtx.App.Cmd().Handle(name, handler)
	}
}

func CommandNames() []string {
	return []string{
{{- range .Services }}
{{- range .RPCs }}
		"{{ .CommandName }}",
{{- end }}
{{- end }}
	}
}

var _ = types.Empty{}
