// Code generated by scorix.
package {{ .Service.Package }}

import (
	"context"

	"{{ .Module }}/internal/svc"
	"{{ .Module }}/internal/types"
)

type {{ .RPC.LogicName }} struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func New{{ .RPC.LogicName }}(ctx context.Context, svcCtx *svc.ServiceContext) *{{ .RPC.LogicName }} {
	return &{{ .RPC.LogicName }}{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *{{ .RPC.LogicName }}) {{ .RPC.MethodName }}(params *{{ .RPC.RequestGoType }}) (*{{ .RPC.ResultGoType }}, error) {
	return nil, nil
}
