// Code generated by scorix. DO NOT EDIT.
package {{ .Package }}

import (
	"context"
	"database/sql"
{{- if .SQL.NeedsTimeImport }}
	"time"
{{- end }}

{{- if .SQL.NeedsUUIDHook }}

	"github.com/google/uuid"
{{- end }}
	"github.com/jmoiron/sqlx"

	scorixsqlx "github.com/tradalab/scorix/module/sqlx"
)

const (
	{{ lowerFirst .Table.GoName }}FindOneSQL  = {{ printf "%q" .SQL.FindOneSQL }}
	{{ lowerFirst .Table.GoName }}FindAllSQL  = {{ printf "%q" .SQL.FindAllSQL }}
	{{ lowerFirst .Table.GoName }}FindManySQL = {{ printf "%q" .SQL.FindManyBaseSQL }}
	{{ lowerFirst .Table.GoName }}InsertSQL   = {{ printf "%q" .SQL.InsertSQL }}
	{{ lowerFirst .Table.GoName }}UpdateSQL   = {{ printf "%q" .SQL.UpdateSQL }}
	{{ lowerFirst .Table.GoName }}DeleteSQL   = {{ printf "%q" .SQL.DeleteSQL }}
{{- range .SQL.FindOneByCols }}
	{{ lowerFirst $.Table.GoName }}FindOneBy{{ .GoName }}SQL = {{ printf "%q" .SQL }}
{{- end }}
)

type (
	// {{ lowerFirst .Table.GoName }}Model — per-table CRUD only. Relations stitched in internal/logic/.
	{{ lowerFirst .Table.GoName }}Model interface {
		Insert(ctx context.Context, data *{{ .Table.GoName }}) (sql.Result, error)
		FindOne(ctx context.Context, id {{ .Table.PKGoType }}) (*{{ .Table.GoName }}, error)
		FindMany(ctx context.Context, ids []{{ .Table.PKGoType }}) ([]*{{ .Table.GoName }}, error)
		FindAll(ctx context.Context) ([]*{{ .Table.GoName }}, error)
{{- range .SQL.FindOneByCols }}
		FindOneBy{{ .GoName }}(ctx context.Context, {{ .ParamName }} {{ .GoType }}) (*{{ $.Table.GoName }}, error)
{{- end }}
		Update(ctx context.Context, data *{{ .Table.GoName }}) error
		Delete(ctx context.Context, id {{ .Table.PKGoType }}) error
	}

	// conn is a provider (not a bound handle) so callers can wire models in
	// NewServiceContext before OnLoad opens the DB. scorixsqlx.From(ctx, m.conn)
	// substitutes the *sqlx.Tx attached by Module.WithTx when present.
	default{{ .Table.GoName }}Model struct {
		conn func() scorixsqlx.Conn
	}

	{{ .Table.GoName }} struct {
{{- range .Table.Columns }}
		{{ .GoName }} {{ .GoType }} `db:"{{ .Name }}" json:"{{ .JSONTag }}"`
{{- end }}
	}
)

func newDefault{{ .Table.GoName }}Model(conn func() scorixsqlx.Conn) *default{{ .Table.GoName }}Model {
	return &default{{ .Table.GoName }}Model{conn: conn}
}

func (m *default{{ .Table.GoName }}Model) Insert(ctx context.Context, data *{{ .Table.GoName }}) (sql.Result, error) {
{{- if .SQL.NeedsUUIDHook }}
	if data.{{ .Table.PKGoName }} == "" {
		data.{{ .Table.PKGoName }} = uuid.NewString()
	}
{{- end }}
{{- if .SQL.HasCreatedAt }}
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
{{- end }}
{{- if .SQL.HasUpdatedAt }}
	data.UpdatedAt = time.Now()
{{- end }}
	return scorixsqlx.From(ctx, m.conn).ExecContext(ctx, {{ lowerFirst .Table.GoName }}InsertSQL,
{{- range .SQL.InsertFields }}
		data.{{ .GoName }},
{{- end }}
	)
}

func (m *default{{ .Table.GoName }}Model) FindOne(ctx context.Context, id {{ .Table.PKGoType }}) (*{{ .Table.GoName }}, error) {
	var resp {{ .Table.GoName }}
	err := sqlx.GetContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, {{ lowerFirst .Table.GoName }}FindOneSQL, id)
	return &resp, err
}

func (m *default{{ .Table.GoName }}Model) FindMany(ctx context.Context, ids []{{ .Table.PKGoType }}) ([]*{{ .Table.GoName }}, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	conn := scorixsqlx.From(ctx, m.conn)
	query, args, err := sqlx.In({{ lowerFirst .Table.GoName }}FindManySQL, ids)
	if err != nil {
		return nil, err
	}
	query = conn.Rebind(query)
	var resp []*{{ .Table.GoName }}
	err = sqlx.SelectContext(ctx, conn, &resp, query, args...)
	return resp, err
}

func (m *default{{ .Table.GoName }}Model) FindAll(ctx context.Context) ([]*{{ .Table.GoName }}, error) {
	var resp []*{{ .Table.GoName }}
	err := sqlx.SelectContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, {{ lowerFirst .Table.GoName }}FindAllSQL)
	return resp, err
}
{{ range .SQL.FindOneByCols }}
func (m *default{{ $.Table.GoName }}Model) FindOneBy{{ .GoName }}(ctx context.Context, {{ .ParamName }} {{ .GoType }}) (*{{ $.Table.GoName }}, error) {
	var resp {{ $.Table.GoName }}
	err := sqlx.GetContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, {{ lowerFirst $.Table.GoName }}FindOneBy{{ .GoName }}SQL, {{ .ParamName }})
	return &resp, err
}
{{ end }}
func (m *default{{ .Table.GoName }}Model) Update(ctx context.Context, data *{{ .Table.GoName }}) error {
{{- if .SQL.HasUpdatedAt }}
	data.UpdatedAt = time.Now()
{{- end }}
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, {{ lowerFirst .Table.GoName }}UpdateSQL,
{{- range .SQL.UpdateFields }}
		data.{{ .GoName }},
{{- end }}
		data.{{ .Table.PKGoName }},
	)
	return err
}

func (m *default{{ .Table.GoName }}Model) Delete(ctx context.Context, id {{ .Table.PKGoType }}) error {
{{- if .SQL.DeleteIsSoft }}
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, {{ lowerFirst .Table.GoName }}DeleteSQL, time.Now(), id)
{{- else }}
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, {{ lowerFirst .Table.GoName }}DeleteSQL, id)
{{- end }}
	return err
}
