// Code generated by scorix. DO NOT EDIT.
package {{ .Package }}

import _ "embed"

// SchemaSQL holds the embedded contents of {{ .SchemaFile }}. Pass to
// scorixsqlx.WithSchema so the sqlx module installs it during OnLoad.
// Script must be idempotent (CREATE TABLE/INDEX IF NOT EXISTS).
//
//go:embed {{ .SchemaFile }}
var SchemaSQL string
