// Code generated by scorix.
package svc

import (
	"context"
	"{{ .Module }}/internal/config"
{{- if .Proto.HasMiddleware }}
	"{{ .Module }}/internal/middleware"
{{- end }}
	// scorix:model:imports:start
	// scorix:model:imports:end
	scorix "github.com/tradalab/scorix/kernel"
	scorix_config "github.com/tradalab/scorix/kernel/core/config"
)

type ServiceContext struct {
	Cfg *config.Config
	App scorix.App
{{- range .Proto.Middlewares }}
	{{ . }}Middleware func(func(context.Context, any) (any, error)) func(context.Context, any) (any, error)
{{- end }}
	// scorix:model:fields:start
	// scorix:model:fields:end
}

func NewServiceContext(cfg *scorix_config.Config, app scorix.App) *ServiceContext {
	// scorix:model:init:start
	// scorix:model:init:end
	return &ServiceContext{
		Cfg: &config.Config{Config: *cfg},
		App: app,
{{- range .Proto.Middlewares }}
		{{ . }}Middleware: middleware.{{ . }}Middleware,
{{- end }}
		// scorix:model:assigns:start
		// scorix:model:assigns:end
	}
}
