// Code generated by scorix. DO NOT EDIT.
package types

{{- if not .Proto.HasEmpty }}
type Empty struct{}
{{ end }}

{{ range .Proto.Messages -}}
type {{ .GoName }} struct {
{{- range .Fields }}
	{{ .GoName }} {{ .GoType }} `json:"{{ .JSONName }}"`
{{- end }}
}

{{ end -}}
