/**
 * Code generated by scorix. DO NOT EDIT.
 */
{{- if not .Proto.HasEmpty }}
export type Empty = Record<string, never>;
{{ end }}
{{- range .Proto.Messages }}
export interface {{ .GoName }} {
{{- range .Fields }}
  {{ .JSONName }}{{ if .Repeated }}?{{ end }}: {{ .TSType }};
{{- end }}
}
{{ end }}
